import { createHash,randomBytes,randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getAdminIdentity,hasValidRequestOrigin } from "@/lib/server/admin-auth";
import { getDatabase } from "@/lib/server/database";
import { queueAndSendEmail } from "@/lib/server/email";
import { hashPassword } from "@/lib/server/passwords";
export const runtime="nodejs";export const dynamic="force-dynamic";
const input=z.discriminatedUnion("action",[z.object({action:z.literal("invite"),email:z.string().email(),displayName:z.string().trim().min(2).max(150),role:z.enum(["ADMIN","SUPER_ADMIN"])}),z.object({action:z.literal("status"),id:z.string(),status:z.enum(["ACTIVE","SUSPENDED","DISABLED"])}),z.object({action:z.literal("revoke_sessions"),id:z.string()}),z.object({action:z.literal("reset"),id:z.string()})]);
export async function GET(){if(!await getAdminIdentity("SUPER_ADMIN"))return NextResponse.json({ok:false},{status:403});const database=await getDatabase();const users=await database.query(`SELECT u.id,u.email,u.display_name,u.system_role,u.status,u.created_at,COUNT(s.id) FILTER (WHERE s.revoked_at IS NULL AND s.expires_at>CURRENT_TIMESTAMP)::int AS active_sessions,MAX(s.last_seen_at) AS last_seen_at FROM users u LEFT JOIN sessions s ON s.user_id=u.id WHERE u.system_role IN ('ADMIN','SUPER_ADMIN') GROUP BY u.id ORDER BY u.created_at`);return NextResponse.json({ok:true,users:users.rows})}
export async function POST(request:Request){if(!hasValidRequestOrigin(request))return NextResponse.json({ok:false},{status:403});const actor=await getAdminIdentity("SUPER_ADMIN");if(!actor)return NextResponse.json({ok:false},{status:403});const parsed=input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({ok:false,message:"Invalid team operation."},{status:422});const database=await getDatabase(),data=parsed.data;let activationUrl:string|undefined;
 try{await database.transaction(async tx=>{if(data.action==="invite"){const id=randomUUID(),token=randomBytes(32).toString("base64url"),tokenHash=createHash("sha256").update(token).digest("hex"),placeholder=await hashPassword(randomBytes(32).toString("base64url"));await tx.query("INSERT INTO users (id,email,display_name,system_role,status) VALUES ($1,$2,$3,$4,'INVITED')",[id,data.email.toLowerCase(),data.displayName,data.role]);await tx.query("INSERT INTO user_credentials (user_id,password_hash,reset_token_hash,reset_token_expires_at) VALUES ($1,$2,$3,CURRENT_TIMESTAMP+INTERVAL '24 hours')",[id,placeholder,tokenHash]);activationUrl=`${publicOrigin(request)}/admin/activate?token=${encodeURIComponent(token)}`;await queueAndSendEmail(tx,{templateKey:"admin_invitation",recipient:data.email,subject:"Activate your Hi-Five administrator account",text:`You were invited to the Hi-Five administrator workspace. Activate your account within 24 hours: ${activationUrl}`})}else if(data.action==="status"){if(data.id===actor.id&&data.status!=="ACTIVE")throw new Error("You cannot disable your own account.");await tx.query("UPDATE users SET status=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND system_role IN ('ADMIN','SUPER_ADMIN')",[data.id,data.status]);if(data.status!=="ACTIVE")await tx.query("UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=$1 AND revoked_at IS NULL",[data.id])}else if(data.action==="revoke_sessions")await tx.query("UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=$1 AND revoked_at IS NULL",[data.id]);else{const token=randomBytes(32).toString("base64url"),tokenHash=createHash("sha256").update(token).digest("hex"),found=await tx.query<{email:string}>("SELECT email FROM users WHERE id=$1 AND system_role IN ('ADMIN','SUPER_ADMIN')",[data.id]);if(!found.rows[0])throw new Error("Administrator not found.");await tx.query("UPDATE user_credentials SET reset_token_hash=$2,reset_token_expires_at=CURRENT_TIMESTAMP+INTERVAL '24 hours' WHERE user_id=$1",[data.id,tokenHash]);activationUrl=`${publicOrigin(request)}/admin/activate?token=${encodeURIComponent(token)}`;await queueAndSendEmail(tx,{templateKey:"admin_password_reset",recipient:found.rows[0].email,subject:"Reset your Hi-Five administrator password",text:`Reset your administrator password within 24 hours: ${activationUrl}`})}await tx.query("INSERT INTO audit_events (id,actor_user_id,action,aggregate_type,aggregate_id,after_json) VALUES ($1,$2,$3,'ADMIN_USER',$4,$5)",[randomUUID(),actor.id,`ADMIN_${data.action.toUpperCase()}`,"id" in data?data.id:"new",data])});return NextResponse.json({ok:true,activationUrl})}catch(error){const message=error instanceof Error&&/own account|not found/i.test(error.message)?error.message:/unique|duplicate/i.test(String(error))?"That administrator email already exists.":"The team change could not be saved.";return NextResponse.json({ok:false,message},{status:422})}}
function publicOrigin(request:Request){const configured=process.env.NEXT_PUBLIC_SITE_URL?.trim();if(configured)return configured.replace(/\/$/,"");const proto=request.headers.get("x-forwarded-proto")||new URL(request.url).protocol.replace(":","");const host=request.headers.get("x-forwarded-host")||request.headers.get("host")||new URL(request.url).host;return `${proto}://${host}`}
