import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { hasValidRequestOrigin } from "@/lib/server/admin-auth";
import { getBuyerIdentity } from "@/lib/server/buyer-auth";
import { getDatabase } from "@/lib/server/database";
export const runtime="nodejs";export const dynamic="force-dynamic";
const address=z.object({label:z.string().trim().min(2).max(80),recipient:z.string().trim().min(2).max(150),line1:z.string().trim().min(3).max(200),line2:z.string().trim().max(200).default(""),city:z.string().trim().min(2).max(120),region:z.string().trim().min(2).max(100),postalCode:z.string().trim().min(2).max(30),countryCode:z.string().trim().length(2),phone:z.string().trim().max(40).default(""),isDefault:z.boolean().default(false)});
export async function GET(){const buyer=await getBuyerIdentity();if(!buyer)return NextResponse.json({ok:false},{status:401});const database=await getDatabase();const [addresses,loyalty]=await Promise.all([database.query("SELECT id,label,recipient,line1,line2,city,region,postal_code,country_code,phone,is_default FROM customer_addresses WHERE organization_id=$1 ORDER BY is_default DESC,created_at",[buyer.organizationId]),database.query("SELECT points_balance,tier FROM loyalty_accounts WHERE organization_id=$1",[buyer.organizationId])]);return NextResponse.json({ok:true,addresses:addresses.rows,loyalty:loyalty.rows[0]??{points_balance:0,tier:"MEMBER"}})}
export async function POST(request:Request){if(!hasValidRequestOrigin(request))return NextResponse.json({ok:false},{status:403});const buyer=await getBuyerIdentity();if(!buyer)return NextResponse.json({ok:false},{status:401});const parsed=address.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({ok:false,message:"Complete the required address fields."},{status:422});const data=parsed.data,database=await getDatabase(),id=randomUUID();await database.transaction(async tx=>{if(data.isDefault)await tx.query("UPDATE customer_addresses SET is_default=FALSE WHERE organization_id=$1",[buyer.organizationId]);await tx.query("INSERT INTO customer_addresses (id,organization_id,label,recipient,line1,line2,city,region,postal_code,country_code,phone,is_default) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)",[id,buyer.organizationId,data.label,data.recipient,data.line1,data.line2,data.city,data.region,data.postalCode,data.countryCode.toUpperCase(),data.phone,data.isDefault])});return NextResponse.json({ok:true,id},{status:201})}
export async function DELETE(request:Request){if(!hasValidRequestOrigin(request))return NextResponse.json({ok:false},{status:403});const buyer=await getBuyerIdentity();if(!buyer)return NextResponse.json({ok:false},{status:401});const id=new URL(request.url).searchParams.get("id");if(!id)return NextResponse.json({ok:false},{status:422});await (await getDatabase()).query("DELETE FROM customer_addresses WHERE id=$1 AND organization_id=$2",[id,buyer.organizationId]);return NextResponse.json({ok:true})}
