"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { Building2,Check,Mail,MessageCircle,Search,Send,UserRound } from "lucide-react";
type Message={id:string;sender:"buyer"|"admin";body:string;sentAt:string};
type Conversation={id:string;company:string;contact:string;email:string;status:"OPEN"|"CLOSED";unread_by_admin:number;unread_by_buyer:number;updated_at:string;messages:Message[]};
export function AdminChatInbox(){
 const [conversations,setConversations]=useState<Conversation[]>([]),[activeId,setActiveId]=useState(""),[query,setQuery]=useState(""),[reply,setReply]=useState(""),[notice,setNotice]=useState("Loading conversations…");
 const load=useCallback(async()=>{const response=await fetch("/api/chat/conversations",{cache:"no-store"});const result=await response.json() as {conversations?:Conversation[]};if(!response.ok)throw new Error();const next=result.conversations??[];setConversations(next);setActiveId(current=>current||next[0]?.id||"");setNotice(next.length?"":"No conversations yet.")},[]);
 useEffect(()=>{const initial=window.setTimeout(()=>void load().catch(()=>setNotice("Conversations could not be loaded.")),0);const timer=window.setInterval(()=>void load(),15000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load]);
 const active=useMemo(()=>conversations.find(item=>item.id===activeId),[activeId,conversations]),filtered=conversations.filter(item=>`${item.company} ${item.contact} ${item.email}`.toLowerCase().includes(query.toLowerCase())),unread=conversations.reduce((sum,item)=>sum+item.unread_by_admin,0);
 const select=async(id:string)=>{setActiveId(id);await fetch("/api/chat/conversations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:id,action:"read"})});await load()};
 const send=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!active||!reply.trim())return;const response=await fetch("/api/chat/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:active.id,message:reply.trim()})});if(response.ok){setReply("");await load()}};
 const toggle=async()=>{if(!active)return;await fetch("/api/chat/conversations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:active.id,action:active.status==="OPEN"?"close":"open"})});await load()};
 return <><div className="admin-section-head"><div><span className="eyebrow">Buyer conversations</span><h2>CHAT INBOX.</h2><p>Persistent conversations shared by both administrator roles.</p></div><div className="chat-admin-status configured"><Mail/><div><small>Email delivery</small><strong>Outbox and Resend-ready notifications</strong></div><span>{unread} unread</span></div></div>{notice&&<div className="gate-message">{notice}</div>}<section className="admin-chat-shell"><aside className="admin-chat-list"><div className="admin-chat-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search conversations"/></div>{filtered.map(item=><button className={item.id===activeId?"active":""} key={item.id} onClick={()=>void select(item.id)}><div className="chat-avatar">{item.company.slice(0,2).toUpperCase()}</div><div><strong>{item.company}</strong><span>{item.messages.at(-1)?.body}</span><small>{item.contact} · {new Date(item.updated_at).toLocaleDateString()}</small></div>{item.unread_by_admin>0&&<b>{item.unread_by_admin}</b>}</button>)}</aside><div className="admin-chat-panel">{active?<><header><div><Building2/><div><strong>{active.company}</strong><span>{active.contact} · {active.email}</span></div></div><button onClick={()=>void toggle()}>{active.status==="OPEN"?<><Check/>Close conversation</>:"Reopen conversation"}</button></header><div className="admin-chat-thread">{active.messages.map(item=><div className={`admin-chat-message ${item.sender}`} key={item.id}><span>{item.sender==="admin"?"Hi-Five team":active.contact}</span><p>{item.body}</p><small>{new Date(item.sentAt).toLocaleString()}</small></div>)}</div><form onSubmit={send}><UserRound/><textarea value={reply} onChange={event=>setReply(event.target.value)} placeholder={`Reply to ${active.contact}…`} maxLength={2000} required/><button aria-label="Send reply"><Send/></button></form></>:<div className="admin-chat-placeholder"><MessageCircle/><h3>SELECT A CONVERSATION.</h3><p>Buyer messages and contact details appear here.</p></div>}</div></section></>;
}
