"use client";

import Image from "next/image";
import Link from "next/link";
import { Activity, BarChart3, Bell, Boxes, ChevronRight, CircleDollarSign, FileText, Gift, Globe2, Handshake, LayoutDashboard, LockKeyhole, LogOut, PackageCheck, Plus, Settings, ShieldCheck, ShoppingCart, Sparkles, Store, Tag, Truck, UserRoundCheck, Users } from "lucide-react";
import { useEffect, useState } from "react";
import type { AccessApplication } from "@/components/wholesale-access-gate";
import type { BrandApplication } from "@/app/brands/page";

type Tab="overview"|"orders"|"products"|"customers"|"access"|"loyalty"|"content"|"distributors"|"brands"|"wholesale"|"markets"|"reports"|"operations"|"team"|"security";
type Product={id:string;name:string;sku:string;variant:string;price:number;stock:number;lowAt:number;status:string};
type Order={id:string;customer:string;method:string;status:string;total:number;refunded:number;note:string};
type Content={id:string;type:string;title:string;status:string;date:string};
type DemoState={products:Product[];orders:Order[];content:Content[];points:number;multiplier:number;leads:{company:string;stage:string;owner:string}[]};
const initial:DemoState={products:[{id:"P-1024",name:"Midnight Mint",sku:"NS-MM-06",variant:"Cool Mint / 6mg",price:109.8,stock:8,lowAt:12,status:"Published"},{id:"P-1025",name:"Purple Rush",sku:"HL-PR-05",variant:"Grape Ice / 5%",price:195,stock:34,lowAt:10,status:"Published"},{id:"P-1026",name:"Berry Static",sku:"HL-BS-03",variant:"Mixed Berry / 3mg",price:138,stock:6,lowAt:8,status:"Scheduled"}],orders:[{id:"HF-4821",customer:"Midtown Market",method:"Delivery",status:"Ready to pack",total:1248,refunded:0,note:"Call receiving desk on arrival."},{id:"HF-4820",customer:"Five Points Smoke",method:"Pickup",status:"Processing",total:684.5,refunded:0,note:"Tax certificate on file."},{id:"HF-4819",customer:"Westline Retail",method:"Freight",status:"Shipped",total:2940,refunded:195,note:"One case credited."}],content:[{id:"C-31",type:"Social",title:"Purple Rush just landed",status:"Scheduled",date:"Aug 20 · 4:30 PM"},{id:"C-30",type:"Blog",title:"Build a shelf that moves product",status:"Published",date:"Aug 16 · 9:00 AM"}],points:1,multiplier:2,leads:[{company:"Eastside Tobacco",stage:"Application",owner:"Jamie"},{company:"Gulf Market Supply",stage:"Qualified",owner:"Alex"},{company:"North Loop Retail",stage:"Negotiation",owner:"Alex"}]};
const seededAccess:AccessApplication[]=[{id:"WA-1042",company:"Broadway Market",contact:"Dana Lewis",email:"buyer@broadway.example",phone:"(555) 010-2044",resaleId:"TN-884210",territory:"Tennessee",status:"Pending",submitted:"Aug 17, 2026"},{id:"WA-1039",company:"Lakeview Smoke",contact:"Omar Reed",email:"orders@lakeview.example",phone:"(555) 010-9912",resaleId:"IL-210084",territory:"Illinois",status:"Approved",submitted:"Aug 15, 2026"}];
const seededBrands:BrandApplication[]=[{id:"BR-3184",brand:"Violet Labs",contact:"Nina Patel",email:"sales@violetlabs.example",website:"https://violetlabs.example",categories:"Nicotine pouches",markets:"Southeast US",volume:"$25,000–$100,000",message:"Seeking an independent retail distribution partner.",status:"Review",submitted:"Aug 17, 2026"},{id:"BR-3179",brand:"North Standard",contact:"Eli Brooks",email:"wholesale@northstandard.example",website:"https://northstandard.example",categories:"Pouches and accessories",markets:"United States",volume:"$100,000+",message:"Expanding retail placement in new territories.",status:"Samples requested",submitted:"Aug 14, 2026"}];
const common:[Tab,string,React.ElementType][]=[["overview","Overview",LayoutDashboard],["orders","Orders",ShoppingCart],["products","Products",Boxes],["customers","Customers",Users],["access","Access approvals",ShieldCheck],["loyalty","Loyalty & promos",Gift],["content","Blog & social",Sparkles],["distributors","Distributor CRM",Store],["brands","Brand pipeline",Handshake],["wholesale","Wholesale pricing",Tag],["markets","Markets",Globe2],["reports","Reports & exports",BarChart3],["operations","Operations",Settings]];
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
function Pill({children,tone=""}:{children:React.ReactNode;tone?:string}){return <span className={`admin-pill ${tone}`}>{children}</span>}
function Head({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy?:string;action?:React.ReactNode}){return <div className="admin-section-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>{action}</div>}

export function AdminDashboard({superAdmin=false}:{superAdmin?:boolean}){
 const [ready,setReady]=useState(false); const [session,setSession]=useState(false); const [tab,setTab]=useState<Tab>("overview"); const [state,setState]=useState(initial); const [toast,setToast]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>{const saved=localStorage.getItem("hifive-admin-demo");if(saved)setState(JSON.parse(saved));setSession(sessionStorage.getItem(superAdmin?"hf-super":"hf-admin")==="1");setReady(true)},0);return()=>window.clearTimeout(timer)},[superAdmin]);
 const update=(next:DemoState,message:string)=>{setState(next);localStorage.setItem("hifive-admin-demo",JSON.stringify(next));setToast(message);setTimeout(()=>setToast(""),2200)};
 const nav=superAdmin?[...common,["team","Admin users",UserRoundCheck] as [Tab,string,React.ElementType],["security","Security & audit",LockKeyhole] as [Tab,string,React.ElementType]]:common;
 if(!ready)return null;
 if(!session)return <main className="admin-login"><section><Image src="/images/hifive-logo.png" alt="Hi-Five Supply" width={250} height={136}/><div><Pill tone="purple">Interactive client preview</Pill><h1>CONTROL THE<br/><em>WHOLE FLOW.</em></h1><p>One connected view of catalog, inventory, fulfillment, customers, loyalty, content, distributors, and growth.</p></div><small>Preview data is stored only in this browser. Production authentication and database connections follow client approval.</small></section><form onSubmit={(event)=>{event.preventDefault();sessionStorage.setItem(superAdmin?"hf-super":"hf-admin","1");setSession(true)}}><span className="eyebrow">Protected workspace preview</span><h2>WELCOME BACK.</h2><label>Email<input defaultValue={superAdmin?"alex@hifivesupply.com":"jamie@hifivesupply.com"}/></label><label>Password<input type="password" defaultValue="preview123"/></label><button className="button primary full">Sign in as {superAdmin?"super admin":"admin"}</button><button type="button" className="link-button">Forgot password?</button><div className="login-proof"><ShieldCheck/>Role-based preview · Session controls · Reset-ready</div></form></main>;
 return <main className="admin-shell"><aside><Link href="/"><Image src="/images/hifive-logo.png" alt="Hi-Five Supply" width={170} height={92}/></Link><Pill tone="purple">{superAdmin?"Super admin":"Admin workspace"}</Pill><nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={17}/><span>{label}</span></button>)}</nav></aside><section className="admin-main"><header><div><span className="eyebrow">Operations center</span><h1>{nav.find(([id])=>id===tab)?.[1]}</h1></div><div><Pill tone="warn">Preview data</Pill><Link href="/" className="admin-store-link">Storefront</Link><button className="icon-button" onClick={()=>{sessionStorage.removeItem(superAdmin?"hf-super":"hf-admin");setSession(false)}}><LogOut size={18}/></button></div></header>{toast&&<div className="toast"><PackageCheck/>{toast}</div>}
 {tab==="overview"&&<Overview state={state} setTab={setTab}/>} {tab==="orders"&&<Orders state={state} update={update}/>} {tab==="products"&&<Products state={state} update={update}/>} {tab==="customers"&&<Customers/>} {tab==="access"&&<AccessApprovals/>} {tab==="loyalty"&&<Loyalty state={state} update={update}/>} {tab==="content"&&<ContentStudio state={state} update={update}/>} {tab==="distributors"&&<Distributors state={state} update={update}/>} {tab==="brands"&&<BrandPipeline/>} {tab==="wholesale"&&<Capability title="PRICING THAT SCALES." icon={<Tag/>} items={["Account-specific price books","Case and volume tiers","Minimum order rules","Net terms and tax status"]}/>} {tab==="markets"&&<Capability title="SELL WHERE YOU SHOULD." icon={<Globe2/>} items={["United States · USD · Active","Canada · CAD · Review","UAE · AED · Preview","Jurisdiction and shipping restrictions"]}/>} {tab==="reports"&&<Reports state={state}/>} {tab==="operations"&&<Capability title="RUN THE DAY." icon={<Settings/>} items={["Pickup and delivery windows","Notification and email templates","Authorize.net connection point","AgeChecker.net connection point","Privacy export and deletion workflows"]}/>} {tab==="team"&&superAdmin&&<Capability title="ACCESS WITH INTENT." icon={<UserRoundCheck/>} items={["Invite administrators","Assign scoped permissions","Review active sessions","Revoke user access"]}/>} {tab==="security"&&superAdmin&&<Capability title="SECURITY & RECOVERY." icon={<LockKeyhole/>} items={["Audit log and CSV export","Rate limiting and event monitoring","Webhook logs and retry queue","Database backup and recovery readiness"]}/>} </section></main>
}

function Overview({state,setTab}:{state:DemoState;setTab:(tab:Tab)=>void}){const revenue=state.orders.reduce((sum,o)=>sum+o.total-o.refunded,0);const low=state.products.filter(p=>p.stock<=p.lowAt);return <><div className="stat-grid"><button onClick={()=>setTab("orders")}><small>Revenue in view</small><strong>{money(revenue)}</strong><span>Across {state.orders.length} active orders <ChevronRight/></span></button><button onClick={()=>setTab("orders")}><small>Open fulfillment</small><strong>{state.orders.filter(o=>o.status!=="Shipped").length}</strong><span>Pickup, delivery, and freight</span></button><button onClick={()=>setTab("products")}><small>Low stock</small><strong>{low.length}</strong><span className="danger">{low.map(p=>p.sku).join(" · ")}</span></button><button onClick={()=>setTab("loyalty")}><small>Loyalty members</small><strong>1,284</strong><span>84,420 points outstanding</span></button></div><div className="admin-grid"><article className="admin-card"><Head eyebrow="7-day performance" title="ORDER VELOCITY"/><div className="bar-chart">{[42,54,48,77,65,88,71,96,82,100,79,92].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></article><article className="admin-card"><Head eyebrow="Live activity" title="RIGHT NOW"/>{["Purple Rush inventory updated","Social post scheduled","Pickup HF-4820 confirmed","Daily backup checkpoint complete"].map((item,i)=><div className="activity-row" key={item}><Activity/><div><b>{item}</b><small>{i*14+8} minutes ago</small></div></div>)}</article></div><div className="health-grid"><article><ShieldCheck/><div><b>Access controls</b><small>Role map preview active</small></div></article><article><Truck/><div><b>Fulfillment</b><small>3 queues represented</small></div></article><article><Bell/><div><b>Alerts</b><small>{low.length} low-stock events</small></div></article><article><CircleDollarSign/><div><b>Payments</b><small>Authorize.net pending</small></div></article></div></>}
function Orders({state,update}:{state:DemoState;update:(next:DemoState,message:string)=>void}){return <><Head eyebrow="Orders & fulfillment" title="EVERY ORDER. ONE FLOW." copy="Manage pickup, delivery, freight, status, notes, cancellations, and refund previews." action={<button className="admin-button">Export orders</button>}/><div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Fulfillment</th><th>Status</th><th>Total</th><th>Refund</th></tr></thead><tbody>{state.orders.map(order=><tr key={order.id}><td><b>{order.id}</b><small>{order.note}</small></td><td>{order.customer}</td><td><Pill>{order.method}</Pill></td><td><select value={order.status} onChange={e=>update({...state,orders:state.orders.map(o=>o.id===order.id?{...o,status:e.target.value}:o)},`${order.id} moved to ${e.target.value}`)}><option>Processing</option><option>Ready to pack</option><option>Ready for pickup</option><option>Shipped</option><option>Completed</option><option>Cancelled</option></select></td><td>{money(order.total)}</td><td><button className="link-button" onClick={()=>update({...state,orders:state.orders.map(o=>o.id===order.id?{...o,refunded:o.refunded?0:Math.min(195,o.total)}:o)},"Refund preview recorded")}>{order.refunded?money(order.refunded):"Record"}</button></td></tr>)}</tbody></table></div></>}
function Products({state,update}:{state:DemoState;update:(next:DemoState,message:string)=>void}){const add=()=>update({...state,products:[...state.products,{id:`P-${Date.now()}`,name:"New catalog item",sku:"HF-NEW",variant:"Standard",price:120,stock:24,lowAt:8,status:"Draft"}]},"Draft product created");return <><Head eyebrow="Catalog & inventory" title="PRODUCT CONTROL." copy="Create, publish, schedule, and manage SKU-level wholesale inventory." action={<div className="admin-actions"><button className="admin-button">Import CSV</button><button className="admin-button primary" onClick={add}><Plus/>New product</button></div>}/><div className="inventory-grid">{state.products.map(product=><article className="inventory-card" key={product.id}><div className="inventory-art"><span>HF</span></div><Pill tone={product.status==="Published"?"good":"warn"}>{product.status}</Pill><h3>{product.name}</h3><small>{product.sku} · {product.variant}</small><div><span><small>Case price</small><b>{money(product.price)}</b></span><span><small>Stock</small><b className={product.stock<=product.lowAt?"danger":""}>{product.stock}</b></span><span><small>Alert at</small><b>{product.lowAt}</b></span></div><button className="link-button" onClick={()=>update({...state,products:state.products.map(p=>p.id===product.id?{...p,stock:p.stock+12}:p)},`${product.name} inventory updated`)}>Restock +12</button></article>)}</div></>}
function Customers(){return <><Head eyebrow="Customer accounts" title="KNOW THE CUSTOMER." copy="Account contacts, addresses, order history, tier, and loyalty balance."/><div className="customer-grid">{[["Midtown Market","buyer@midtown.example","Gold","22 orders"],["Five Points Smoke","ops@fivepoints.example","Silver","14 orders"],["Westline Retail","orders@westline.example","Member","7 orders"]].map(([name,email,tier,orders])=><article className="admin-card" key={name}><div className="avatar">{name.slice(0,2).toUpperCase()}</div><h3>{name}</h3><p>{email}</p><div className="customer-stats"><span><small>Tier</small><b>{tier}</b></span><span><small>History</small><b>{orders}</b></span></div><button className="link-button">View account</button></article>)}</div></>}
function AccessApprovals(){
 const [applications,setApplications]=useState<AccessApplication[]>(seededAccess);
 useEffect(()=>{const timer=window.setTimeout(()=>{const saved=JSON.parse(localStorage.getItem("hifive-access-applications")||"[]") as AccessApplication[];setApplications([...saved,...seededAccess.filter(seed=>!saved.some(item=>item.id===seed.id))])},0);return()=>window.clearTimeout(timer)},[]);
 const change=(id:string,status:AccessApplication["status"])=>{const next=applications.map(item=>item.id===id?{...item,status}:item);setApplications(next);localStorage.setItem("hifive-access-applications",JSON.stringify(next))};
 return <><Head eyebrow="Private wholesale network" title="APPROVE WHO GETS IN." copy="Review business identity, resale credentials, territory, and account fit before unlocking catalog and case pricing." action={<Pill tone="warn">{applications.filter(item=>item.status==="Pending").length} pending</Pill>}/><div className="admin-table-wrap"><table><thead><tr><th>Business</th><th>Contact</th><th>Credentials</th><th>Territory</th><th>Submitted</th><th>Status</th><th>Decision</th></tr></thead><tbody>{applications.map(item=><tr key={item.id}><td><b>{item.company}</b><small>{item.id}</small></td><td>{item.contact}<small>{item.email} · {item.phone}</small></td><td><b>{item.resaleId}</b><small>Verification preview</small></td><td>{item.territory}</td><td>{item.submitted}</td><td><Pill tone={item.status==="Approved"?"good":item.status==="Declined"?"":"warn"}>{item.status}</Pill></td><td><div className="decision-actions"><button onClick={()=>change(item.id,"Approved")}>Approve</button><button onClick={()=>change(item.id,"Declined")}>Decline</button></div></td></tr>)}</tbody></table></div></>
}
function BrandPipeline(){
 const [brands,setBrands]=useState<BrandApplication[]>(seededBrands);
 useEffect(()=>{const timer=window.setTimeout(()=>{const saved=JSON.parse(localStorage.getItem("hifive-brand-applications")||"[]") as BrandApplication[];setBrands([...saved,...seededBrands.filter(seed=>!saved.some(item=>item.id===seed.id))])},0);return()=>window.clearTimeout(timer)},[]);
 const change=(id:string,status:BrandApplication["status"])=>{const next=brands.map(item=>item.id===id?{...item,status}:item);setBrands(next);localStorage.setItem("hifive-brand-applications",JSON.stringify(next))};
 const stages:BrandApplication["status"][]=["New","Review","Samples requested","Approved"];
 return <><Head eyebrow="Brand partnerships" title="FIND THE NEXT FAST MOVER." copy="Review brand introductions, commercial fit, samples, territories, and onboarding decisions from one buying pipeline." action={<Link href="/brands" className="admin-button">Public brand page</Link>}/><div className="pipeline brand-pipeline">{stages.map(stage=><section key={stage}><h3>{stage}<span>{brands.filter(item=>item.status===stage).length}</span></h3>{brands.filter(item=>item.status===stage).map(item=><article key={item.id}><small>{item.id} · {item.submitted}</small><b>{item.brand}</b><p>{item.categories}<br/>{item.markets} · {item.volume}</p><a href={item.website} target="_blank">View website</a><select value={item.status} onChange={event=>change(item.id,event.target.value as BrandApplication["status"])}><option>New</option><option>Review</option><option>Samples requested</option><option>Approved</option><option>Declined</option></select></article>)}</section>)}</div></>
}
function Loyalty({state,update}:{state:DemoState;update:(next:DemoState,message:string)=>void}){return <><Head eyebrow="Retention engine" title="LOYALTY & PROMOTIONS." copy="Both admin roles can configure earning, redemption, tiers, multipliers, and promotional codes."/><div className="admin-grid"><article className="admin-card"><h3><Gift/>Program rules</h3><label>Points per $1<input type="number" value={state.points} onChange={e=>update({...state,points:Number(e.target.value)},"Earning rule saved")}/></label><label>Promotional multiplier<input type="number" value={state.multiplier} onChange={e=>update({...state,multiplier:Number(e.target.value)},"Multiplier saved")}/></label><div className="tier-list"><span>Member · 0 points</span><span>Silver · 2,500 points</span><span>Gold · 7,500 points</span></div></article><article className="admin-card"><h3><Tag/>Promotion codes</h3>{["WELCOME10 · 10% · Active","DOUBLEPOINTS · 2× · Scheduled","FREIGHT1500 · Free freight · Draft"].map(item=><div className="setting-row" key={item}><span>{item}</span><ChevronRight/></div>)}<button className="admin-button primary"><Plus/>New promotion</button></article></div></>}
function ContentStudio({state,update}:{state:DemoState;update:(next:DemoState,message:string)=>void}){const add=(type:string)=>update({...state,content:[{id:`C-${Date.now()}`,type,title:type==="Blog"?"New journal draft":"New social card",status:"Draft",date:"Not scheduled"},...state.content]},`${type} draft created`);return <><Head eyebrow="Content studio" title="PUBLISH WITH A PULSE." copy="Both admin roles can create, schedule, publish, and remove blog and social-feed content." action={<div className="admin-actions"><button className="admin-button" onClick={()=>add("Social")}>New social</button><button className="admin-button primary" onClick={()=>add("Blog")}>New article</button></div>}/><div className="content-grid">{state.content.map(item=><article className={item.type==="Blog"?"blog":"social"} key={item.id}><Pill>{item.type} · {item.status}</Pill><h3>{item.title}</h3><small>{item.date}</small><button className="link-button" onClick={()=>update({...state,content:state.content.map(c=>c.id===item.id?{...c,status:c.status==="Published"?"Draft":"Published"}:c)},"Publishing status updated")}>{item.status==="Published"?"Unpublish":"Publish now"}</button></article>)}</div></>}
function Distributors({state,update}:{state:DemoState;update:(next:DemoState,message:string)=>void}){const stages=["Application","Qualified","Negotiation","Approved"];return <><Head eyebrow="Applications & pipeline" title="TURN LEADS INTO ACCOUNTS." copy="Store applications, assign ownership, record notes, and schedule follow-ups."/><div className="pipeline">{stages.map(stage=><section key={stage}><h3>{stage}<span>{state.leads.filter(lead=>lead.stage===stage).length}</span></h3>{state.leads.filter(lead=>lead.stage===stage).map(lead=><article key={lead.company}><small>{lead.owner}</small><b>{lead.company}</b><select value={lead.stage} onChange={e=>update({...state,leads:state.leads.map(l=>l.company===lead.company?{...l,stage:e.target.value}:l)},"Pipeline stage updated")}>{stages.map(option=><option key={option}>{option}</option>)}</select></article>)}</section>)}</div></>}
function Reports({state}:{state:DemoState}){const gross=state.orders.reduce((sum,o)=>sum+o.total,0);return <><Head eyebrow="Analytics & exports" title="SEE WHAT MOVES." copy="Sales, product, inventory, loyalty, and operational reporting preview."/><div className="report-grid"><article><small>Gross sales</small><strong>{money(gross)}</strong><span>Current order window</span></article><article><small>Average order</small><strong>{money(gross/state.orders.length)}</strong><span>Across fulfillment types</span></article><article><small>Units at risk</small><strong>{state.products.filter(p=>p.stock<=p.lowAt).length}</strong><span>Low-stock SKUs</span></article><article><small>Loyalty liability</small><strong>$4,221</strong><span>At current redemption rule</span></article></div><div className="admin-card export-list"><h3><FileText/>CSV exports</h3>{["Orders","Products","Customers","Loyalty ledger","Distributor pipeline","Audit log"].map(item=><button key={item}>{item}<ChevronRight/></button>)}</div></>}
function Capability({title,icon,items}:{title:string;icon:React.ReactNode;items:string[]}){return <><Head eyebrow="Client-preview capability" title={title} copy="This workspace shows the intended operational flow. Production connections activate after approval."/><div className="capability-grid">{items.map((item,index)=><article key={item}>{icon}<span>0{index+1}</span><h3>{item}</h3><p>{index%2?"Configuration and permissions ready for production data.":"Interactive workflow represented in the approved implementation phase."}</p><Pill tone={index===0?"good":"warn"}>{index===0?"Preview active":"Connection ready"}</Pill></article>)}</div></>}
