"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "es" | "ar";
const labels = {
  en: { shop: "Shop wholesale", loyalty: "Loyalty", journal: "Journal", brands: "For brands", story: "Our story", login: "Buyer account", cart: "Cart", kicker: "Wholesale, elevated.", hero: "MOVE PRODUCT. BUILD MOMENTUM.", heroCopy: "A sharper wholesale experience for retailers who want fast-moving inventory, flexible fulfillment, and a partner that picks up the phone.", explore: "Explore the catalog", wholesale: "Open a wholesale account", catalog: { search: "Search product, brand, flavor, collection…", filters: "Filters", sort: "Sort by", featured: "Featured", newest: "Newest", productName: "Product name", all: "All products", brands: "Brands", refine: "Refine catalog", category: "Category", brand: "Brand", collection: "Strength / collection", flavor: "Flavor", clear: "Clear all filters", show: "Show", products: "products", ready: "ready for wholesale", reset: "Reset results", noResults: "No products found", wider: "TRY A WIDER SEARCH.", widerCopy: "Remove a filter or search another product, brand, flavor, or collection.", resetCatalog: "Reset catalog" }, checkout: { kicker: "Cart & checkout", title: "READY WHEN YOU ARE.", order: "Your case order", empty: "Your cart is ready for a first case.", emptyCopy: "Browse the wholesale catalog and add a product to preview the checkout flow.", shop: "Shop catalog", fulfillment: "Fulfillment", question: "How should we get it to you?", pickup: "Pickup", pickupTime: "Ready in 2–4 hours", delivery: "Delivery", deliveryTime: "Calculated by territory", email: "Contact email", po: "Purchase order number", optional: "Optional", total: "Wholesale total", accountPricing: "Confirmed by your rep", submit: "Submit wholesale order", approvedOnly: "Only an approved business account can submit an order." } },
  es: { shop: "Comprar al por mayor", loyalty: "Lealtad", journal: "Revista", brands: "Para marcas", story: "Nuestra historia", login: "Cuenta comercial", cart: "Carrito", kicker: "Mayoreo, elevado.", hero: "MUEVE PRODUCTO. CREA IMPULSO.", heroCopy: "Una experiencia mayorista más ágil para minoristas que buscan inventario de alta rotación, entregas flexibles y un socio presente.", explore: "Explorar el catálogo", wholesale: "Abrir cuenta mayorista", catalog: { search: "Buscar producto, marca, sabor o colección…", filters: "Filtros", sort: "Ordenar", featured: "Destacados", newest: "Más nuevos", productName: "Nombre del producto", all: "Todos", brands: "Marcas", refine: "Afinar catálogo", category: "Categoría", brand: "Marca", collection: "Potencia / colección", flavor: "Sabor", clear: "Borrar filtros", show: "Mostrar", products: "productos", ready: "disponibles al por mayor", reset: "Restablecer", noResults: "No se encontraron productos", wider: "AMPLÍA TU BÚSQUEDA.", widerCopy: "Elimina un filtro o busca otro producto, marca, sabor o colección.", resetCatalog: "Restablecer catálogo" }, checkout: { kicker: "Carrito y pago", title: "LISTO CUANDO TÚ LO ESTÉS.", order: "Tu pedido por cajas", empty: "Tu carrito está listo para la primera caja.", emptyCopy: "Explora el catálogo mayorista y agrega un producto.", shop: "Ver catálogo", fulfillment: "Entrega", question: "¿Cómo lo hacemos llegar?", pickup: "Recogida", pickupTime: "Listo en 2–4 horas", delivery: "Entrega", deliveryTime: "Calculado por territorio", email: "Correo de contacto", po: "Número de orden de compra", optional: "Opcional", total: "Total mayorista", accountPricing: "Confirmado por tu representante", submit: "Enviar pedido mayorista", approvedOnly: "Solo una empresa aprobada puede enviar un pedido." } },
  ar: { shop: "تسوق بالجملة", loyalty: "الولاء", journal: "المجلة", brands: "للعلامات التجارية", story: "قصتنا", login: "حساب المشتري", cart: "السلة", kicker: "تجارة جملة بمستوى أعلى.", hero: "حرّك المنتجات. اصنع الزخم.", heroCopy: "تجربة جملة أكثر ذكاءً للمتاجر التي تريد مخزونًا سريع الحركة وخيارات استلام وتوصيل مرنة وشريكًا موثوقًا.", explore: "استكشف المنتجات", wholesale: "افتح حساب جملة", catalog: { search: "ابحث عن منتج أو علامة أو نكهة أو مجموعة…", filters: "التصفية", sort: "الترتيب", featured: "مميز", newest: "الأحدث", productName: "اسم المنتج", all: "كل المنتجات", brands: "العلامات", refine: "تصفية الكتالوج", category: "الفئة", brand: "العلامة", collection: "القوة / المجموعة", flavor: "النكهة", clear: "مسح الفلاتر", show: "عرض", products: "منتجًا", ready: "متاحًا للجملة", reset: "إعادة الضبط", noResults: "لم يتم العثور على منتجات", wider: "وسّع نطاق البحث.", widerCopy: "أزل أحد الفلاتر أو ابحث عن منتج أو علامة أو نكهة أو مجموعة أخرى.", resetCatalog: "إعادة ضبط الكتالوج" }, checkout: { kicker: "السلة وإتمام الطلب", title: "جاهزون عندما تكون جاهزًا.", order: "طلب الصناديق", empty: "سلتك جاهزة لأول صندوق.", emptyCopy: "تصفح كتالوج الجملة وأضف منتجًا.", shop: "تصفح الكتالوج", fulfillment: "التسليم", question: "كيف نوصله إليك؟", pickup: "الاستلام", pickupTime: "جاهز خلال 2–4 ساعات", delivery: "التوصيل", deliveryTime: "يُحسب حسب المنطقة", email: "بريد التواصل", po: "رقم أمر الشراء", optional: "اختياري", total: "إجمالي الجملة", accountPricing: "يؤكده ممثلك", submit: "إرسال طلب الجملة", approvedOnly: "لا يمكن إرسال الطلب إلا من حساب تجاري معتمد." } },
};

type LanguageContextValue = { language: Language; setLanguage: (value: Language) => void; copy: typeof labels.en };
const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);
  return <LanguageContext.Provider value={{ language, setLanguage, copy: labels[language] }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}
